// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysqctpmhpndlkgoqihtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzcWN0cG1ocG5kbGtnb3FpaHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzM5NDQsImV4cCI6MjA3MDYwOTk0NH0.E6JL7Inu8P2_j64x4ACBoyGFKWMIJH31krWvG5ACmaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});